#############################################################################
# Makefile for building: CheckSum.app/Contents/MacOS/CheckSum
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  CheckSum.pro
# Template: app
# Command: /Users/jie/My/Study/Qt/qt5/qtbase/bin/qmake -o CheckSum.xcodeproj/project.pbxproj CheckSum.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/jie/My/Study/Qt/qt5/qtbase/bin/qmake
CheckSum.xcodeproj/project.pbxproj: CheckSum.pro ../../../qt5/qtbase/mkspecs/macx-clang/qmake.conf ../../../qt5/qtbase/mkspecs/features/spec_pre.prf \
		../../../qt5/qtbase/mkspecs/qdevice.pri \
		../../../qt5/qtbase/mkspecs/features/device_config.prf \
		../../../qt5/qtbase/mkspecs/common/unix.conf \
		../../../qt5/qtbase/mkspecs/common/mac.conf \
		../../../qt5/qtbase/mkspecs/common/macx.conf \
		../../../qt5/qtbase/mkspecs/common/sanitize.conf \
		../../../qt5/qtbase/mkspecs/common/gcc-base.conf \
		../../../qt5/qtbase/mkspecs/common/gcc-base-mac.conf \
		../../../qt5/qtbase/mkspecs/common/clang.conf \
		../../../qt5/qtbase/mkspecs/common/clang-mac.conf \
		../../../qt5/qtbase/mkspecs/qconfig.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_clip2tri.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_clipper.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_libpng.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_poly2tri.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3danimation.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dcore.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dextras.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dinput.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquick.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3drender.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_charts.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_charts_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_designer.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_help.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_location.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_location_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_serialbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_webview.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_webview_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qcocoa.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qicns.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacheif.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacstyle.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtexttospeech_speechosx.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_plugin_scene2d.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_canbusutil.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lprodump.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lrelease-pro.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lupdate-pro.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qgltf.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qml.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmllint.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_repc.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		../../../qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		../../../qt5/qtbase/mkspecs/features/qt_functions.prf \
		../../../qt5/qtbase/mkspecs/features/qt_config.prf \
		../../../qt5/qtbase/mkspecs/macx-clang/qmake.conf \
		../../../qt5/qtbase/mkspecs/macx-xcode/qmake.conf \
		../../../qt5/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt5/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../qt5/qtbase/mkspecs/features/mac/sdk.prf \
		../../../qt5/qtbase/mkspecs/features/toolchain.prf \
		../../../qt5/qtbase/mkspecs/features/mac/toolchain.prf \
		../../../qt5/qtbase/mkspecs/features/default_pre.prf \
		../../../qt5/qtbase/mkspecs/features/mac/default_pre.prf \
		../../../qt5/qtbase/mkspecs/features/resolve_config.prf \
		../../../qt5/qtbase/mkspecs/features/default_post.prf \
		../../../qt5/qtbase/mkspecs/features/mac/default_post.prf \
		../../../qt5/qtbase/mkspecs/features/mac/objective_c.prf \
		../../../qt5/qtbase/mkspecs/features/mac/mac.prf \
		../../../qt5/qtbase/mkspecs/features/warn_on.prf \
		../../../qt5/qtbase/mkspecs/features/qt.prf \
		../../../qt5/qtbase/mkspecs/features/gc_binaries.prf \
		../../../qt5/qtbase/mkspecs/features/resources.prf \
		../../../qt5/qtbase/mkspecs/features/moc.prf \
		../../../qt5/qtbase/mkspecs/features/unix/opengl.prf \
		../../../qt5/qtbase/mkspecs/features/uic.prf \
		../../../qt5/qtbase/mkspecs/features/unix/thread.prf \
		../../../qt5/qtbase/mkspecs/features/qmake_use.prf \
		../../../qt5/qtbase/mkspecs/features/file_copies.prf \
		../../../qt5/qtbase/mkspecs/features/mac/rez.prf \
		../../../qt5/qtbase/mkspecs/features/mac/asset_catalogs.prf \
		../../../qt5/qtbase/mkspecs/features/testcase_targets.prf \
		../../../qt5/qtbase/mkspecs/features/exceptions.prf \
		../../../qt5/qtbase/mkspecs/features/yacc.prf \
		../../../qt5/qtbase/mkspecs/features/lex.prf \
		CheckSum.pro \
		checksum.qrc \
		../../../qt5/qtbase/plugins/styles/libqmacstyle.prl \
		../../../qt5/qtbase/plugins/platforms/libqcocoa.prl \
		../../../qt5/qtbase/plugins/imageformats/libqgif.prl \
		../../../qt5/qtbase/plugins/imageformats/libqicns.prl \
		../../../qt5/qtbase/plugins/imageformats/libqico.prl \
		../../../qt5/qtbase/plugins/imageformats/libqjpeg.prl \
		../../../qt5/qtbase/plugins/imageformats/libqmacheif.prl \
		../../../qt5/qtbase/plugins/imageformats/libqmacjp2.prl \
		../../../qt5/qtbase/plugins/imageformats/libqtga.prl \
		../../../qt5/qtbase/plugins/imageformats/libqtiff.prl \
		../../../qt5/qtbase/plugins/imageformats/libqwbmp.prl \
		../../../qt5/qtbase/plugins/imageformats/libqwebp.prl \
		../../../qt5/qtbase/plugins/bearer/libqgenericbearer.prl \
		../../../qt5/qtbase/plugins/printsupport/libcocoaprintersupport.prl \
		/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Widgets.prl \
		/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Gui.prl \
		/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Network.prl \
		/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Core.prl
	$(QMAKE) -o CheckSum.xcodeproj/project.pbxproj CheckSum.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
../../../qt5/qtbase/mkspecs/features/spec_pre.prf:
../../../qt5/qtbase/mkspecs/qdevice.pri:
../../../qt5/qtbase/mkspecs/features/device_config.prf:
../../../qt5/qtbase/mkspecs/common/unix.conf:
../../../qt5/qtbase/mkspecs/common/mac.conf:
../../../qt5/qtbase/mkspecs/common/macx.conf:
../../../qt5/qtbase/mkspecs/common/sanitize.conf:
../../../qt5/qtbase/mkspecs/common/gcc-base.conf:
../../../qt5/qtbase/mkspecs/common/gcc-base-mac.conf:
../../../qt5/qtbase/mkspecs/common/clang.conf:
../../../qt5/qtbase/mkspecs/common/clang-mac.conf:
../../../qt5/qtbase/mkspecs/qconfig.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_clip2tri.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_clipper.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_libpng.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_openwnn.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_pinyin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_poly2tri.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri:
../../../qt5/qtbase/mkspecs/modules/qt_ext_tcime.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3danimation.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dcore.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dextras.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dinput.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dlogic.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquick.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3drender.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_3drender_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_charts.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_charts_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_datavisualization.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_dbus_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_designer.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_gamepad.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_help.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_location.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_location_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_networkauth.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_positioningquick.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_purchasing.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_repparser.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_repparser_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_script.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_scxml.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_scxml_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_serialbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_texttospeech.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_uiplugin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_webchannel.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_websockets.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_websockets_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_webview.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_webview_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_darwingamepad.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qcocoa.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qicns.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacheif.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmacstyle.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsvg.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtexttospeech_speechosx.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtga.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtiff.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwebgl.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qwebp.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../../qt5/qtbase/mkspecs/modules/qt_plugin_scene2d.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_canbusutil.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lprodump.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lrelease-pro.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lupdate-pro.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qgltf.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qml.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmllint.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_qvkgen.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_repc.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
../../../qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
../../../qt5/qtbase/mkspecs/features/qt_functions.prf:
../../../qt5/qtbase/mkspecs/features/qt_config.prf:
../../../qt5/qtbase/mkspecs/macx-clang/qmake.conf:
../../../qt5/qtbase/mkspecs/macx-xcode/qmake.conf:
../../../qt5/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../qt5/qtbase/mkspecs/features/exclusive_builds.prf:
../../../qt5/qtbase/mkspecs/features/mac/sdk.prf:
../../../qt5/qtbase/mkspecs/features/toolchain.prf:
../../../qt5/qtbase/mkspecs/features/mac/toolchain.prf:
../../../qt5/qtbase/mkspecs/features/default_pre.prf:
../../../qt5/qtbase/mkspecs/features/mac/default_pre.prf:
../../../qt5/qtbase/mkspecs/features/resolve_config.prf:
../../../qt5/qtbase/mkspecs/features/default_post.prf:
../../../qt5/qtbase/mkspecs/features/mac/default_post.prf:
../../../qt5/qtbase/mkspecs/features/mac/objective_c.prf:
../../../qt5/qtbase/mkspecs/features/mac/mac.prf:
../../../qt5/qtbase/mkspecs/features/warn_on.prf:
../../../qt5/qtbase/mkspecs/features/qt.prf:
../../../qt5/qtbase/mkspecs/features/gc_binaries.prf:
../../../qt5/qtbase/mkspecs/features/resources.prf:
../../../qt5/qtbase/mkspecs/features/moc.prf:
../../../qt5/qtbase/mkspecs/features/unix/opengl.prf:
../../../qt5/qtbase/mkspecs/features/uic.prf:
../../../qt5/qtbase/mkspecs/features/unix/thread.prf:
../../../qt5/qtbase/mkspecs/features/qmake_use.prf:
../../../qt5/qtbase/mkspecs/features/file_copies.prf:
../../../qt5/qtbase/mkspecs/features/mac/rez.prf:
../../../qt5/qtbase/mkspecs/features/mac/asset_catalogs.prf:
../../../qt5/qtbase/mkspecs/features/testcase_targets.prf:
../../../qt5/qtbase/mkspecs/features/exceptions.prf:
../../../qt5/qtbase/mkspecs/features/yacc.prf:
../../../qt5/qtbase/mkspecs/features/lex.prf:
CheckSum.pro:
checksum.qrc:
../../../qt5/qtbase/plugins/styles/libqmacstyle.prl:
../../../qt5/qtbase/plugins/platforms/libqcocoa.prl:
../../../qt5/qtbase/plugins/imageformats/libqgif.prl:
../../../qt5/qtbase/plugins/imageformats/libqicns.prl:
../../../qt5/qtbase/plugins/imageformats/libqico.prl:
../../../qt5/qtbase/plugins/imageformats/libqjpeg.prl:
../../../qt5/qtbase/plugins/imageformats/libqmacheif.prl:
../../../qt5/qtbase/plugins/imageformats/libqmacjp2.prl:
../../../qt5/qtbase/plugins/imageformats/libqtga.prl:
../../../qt5/qtbase/plugins/imageformats/libqtiff.prl:
../../../qt5/qtbase/plugins/imageformats/libqwbmp.prl:
../../../qt5/qtbase/plugins/imageformats/libqwebp.prl:
../../../qt5/qtbase/plugins/bearer/libqgenericbearer.prl:
../../../qt5/qtbase/plugins/printsupport/libcocoaprintersupport.prl:
/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Widgets.prl:
/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Gui.prl:
/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Network.prl:
/Users/jie/my/study/qt/qt5/qtbase/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o CheckSum.xcodeproj/project.pbxproj CheckSum.pro -spec macx-xcode

qmake_all: FORCE

