#############################################################################
# Makefile for building: CheckSum.app/Contents/MacOS/CheckSum
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  CheckSum.pro
# Template: app
# Command: /Users/jie/My/Study/Qt/qt5/qtbase/bin/qmake -o CheckSum.xcodeproj/project.pbxproj CheckSum.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/jie/my/study/qt/qt5/qtbase/bin/moc
UIC       = /Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/uic_wrapper.sh
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH       = -I. -I/Users/jie/my/study/qt/qt5/qtbase/include -I/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets -I/Users/jie/my/study/qt/qt5/qtbase/include/QtGui -I/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork -I/Users/jie/my/study/qt/qt5/qtbase/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../qt5/qtbase/mkspecs/macx-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_checksum.cpp moc_predefs.h moc_CalculateFileCheckThread.cpp moc_CalculateTaskManager.cpp moc_checksum.cpp\
	 moc_singleapplication.cpp ui_checksum.h
compiler_rcc_make_all: qrc_checksum.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_checksum.cpp
qrc_checksum.cpp: checksum.qrc \
		/Users/jie/my/study/qt/qt5/qtbase/bin/rcc
	/Users/jie/my/study/qt/qt5/qtbase/bin/rcc -name checksum checksum.qrc -o qrc_checksum.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../qt5/qtbase/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -Wall -W -ffunction-sections -fdata-sections -dM -E -o moc_predefs.h ../../../qt5/qtbase/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CalculateFileCheckThread.cpp moc_CalculateTaskManager.cpp moc_checksum.cpp moc_singleapplication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CalculateFileCheckThread.cpp moc_CalculateTaskManager.cpp moc_checksum.cpp moc_singleapplication.cpp
moc_CalculateFileCheckThread.cpp: CalculateFileCheckThread.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QThread \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QFileInfo \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtGui/QIcon \
		moc_predefs.h \
		/Users/jie/my/study/qt/qt5/qtbase/bin/moc
	/Users/jie/my/study/qt/qt5/qtbase/bin/moc $(DEFINES) --include /Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/moc_predefs.h -I/Users/jie/My/Study/Qt/qt5/qtbase/mkspecs/macx-clang -I/Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum -I/Users/jie/my/study/qt/qt5/qtbase/include -I/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets -I/Users/jie/my/study/qt/qt5/qtbase/include/QtGui -I/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork -I/Users/jie/my/study/qt/qt5/qtbase/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include CalculateFileCheckThread.h -o moc_CalculateFileCheckThread.cpp

moc_CalculateTaskManager.cpp: CalculateTaskManager.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QObject \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QMap \
		CalculateFileCheckThread.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QThread \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QFileInfo \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtGui/QIcon \
		moc_predefs.h \
		/Users/jie/my/study/qt/qt5/qtbase/bin/moc
	/Users/jie/my/study/qt/qt5/qtbase/bin/moc $(DEFINES) --include /Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/moc_predefs.h -I/Users/jie/My/Study/Qt/qt5/qtbase/mkspecs/macx-clang -I/Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum -I/Users/jie/my/study/qt/qt5/qtbase/include -I/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets -I/Users/jie/my/study/qt/qt5/qtbase/include/QtGui -I/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork -I/Users/jie/my/study/qt/qt5/qtbase/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include CalculateTaskManager.h -o moc_CalculateTaskManager.cpp

moc_checksum.cpp: checksum.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QMainWindow \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QFileInfo \
		ui_checksum.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QVariant \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QApplication \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QCheckBox \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QGridLayout \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QHBoxLayout \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QHeaderView \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QLabel \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QLineEdit \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QPushButton \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QSpacerItem \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QSplitter \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QTableView \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QTreeView \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QVBoxLayout \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QWidget \
		MoveLabel.h \
		CalculateTaskManager.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QObject \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QMap \
		CalculateFileCheckThread.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QThread \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtGui/QIcon \
		moc_predefs.h \
		/Users/jie/my/study/qt/qt5/qtbase/bin/moc
	/Users/jie/my/study/qt/qt5/qtbase/bin/moc $(DEFINES) --include /Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/moc_predefs.h -I/Users/jie/My/Study/Qt/qt5/qtbase/mkspecs/macx-clang -I/Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum -I/Users/jie/my/study/qt/qt5/qtbase/include -I/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets -I/Users/jie/my/study/qt/qt5/qtbase/include/QtGui -I/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork -I/Users/jie/my/study/qt/qt5/qtbase/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include checksum.h -o moc_checksum.cpp

moc_singleapplication.cpp: singleapplication.h \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets/QApplication \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtCore/QSharedMemory \
		/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork/QLocalServer \
		moc_predefs.h \
		/Users/jie/my/study/qt/qt5/qtbase/bin/moc
	/Users/jie/my/study/qt/qt5/qtbase/bin/moc $(DEFINES) --include /Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/moc_predefs.h -I/Users/jie/My/Study/Qt/qt5/qtbase/mkspecs/macx-clang -I/Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum -I/Users/jie/my/study/qt/qt5/qtbase/include -I/Users/jie/my/study/qt/qt5/qtbase/include/QtWidgets -I/Users/jie/my/study/qt/qt5/qtbase/include/QtGui -I/Users/jie/my/study/qt/qt5/qtbase/include/QtNetwork -I/Users/jie/my/study/qt/qt5/qtbase/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include singleapplication.h -o moc_singleapplication.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_checksum.h
compiler_uic_clean:
	-$(DEL_FILE) ui_checksum.h
ui_checksum.h: checksum.ui \
		/Users/jie/my/study/qt/qt5/qtbase/bin/uic \
		MoveLabel.h
	/Users/jie/My/Study/Qt/Projects/CheckSum/CheckSum/uic_wrapper.sh checksum.ui -o ui_checksum.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

